image: zazukoians/node-java-jena:v3
before_script:
  - npm ci

pipeline_build:
  stage: build
  environment:
    name: INT
  script:
    - npm run start
  artifacts:
    paths:
      - target/everything.nt
    expire_in: 1 day

