image: zazukoians/node-java-jena
before_script:
  - npm install

stages:
  - build

pipeline_build:
  stage: build
  script:
    - npm run start
  artifacts:
    paths:
      - target/everything.nt
    expire_in: 1 day

